import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import type { Metadata } from 'next';

import AuthContext from '@/app/context/auth-context';
import './globals.css';

export const metadata: Metadata = {
  title: 'Next Chat',
  description: 'Generated by create next app'
};

const inter = Inter({ subsets: ['latin'] });

interface IRootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<IRootLayoutProps> = ({ children }) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Toaster />
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  );
};

export default RootLayout;
